apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-capstone
  labels:
    app: django-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-capstone
  template:
    metadata:
      labels:
        app: django-capstone
    spec:
      containers:
      - name: django-app
        image: django-capstone:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "capstone.settings"
---
apiVersion: v1
kind: Service
metadata:
  name: django-capstone-service
spec:
  selector:
    app: django-capstone
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
